# Generated by Django 5.1.3 on 2024-11-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offset', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinecone_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
