# Generated by Django 5.1.3 on 2024-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_img_url_alter_product_pinecone_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
