# Generated by Django 5.1.3 on 2024-11-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_excelfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='file',
        ),
    ]
